### ISSUE TITLE
ibombshell isolated net

### ISSUE THREAD

**Issue by rusopro** [Telefonica/ibombshell#6]
I want to run ibombshell on isolated lan without internet, i try importing console module but the module try to donwload all functions from internet, Can i run it without internet.

thanks!

**Comment by toolsprods** [comment]
If you are working in Windows, you can use the command _savefunctions_. In order to use that command, you have to be connected to the Internet and have loaded the functions you will use later offline. There you use _savefunctions_ and it will save the functions you used up to the moment for later offline usage.

**Comment by rusopro** [comment]
Can i run ibombshell savefunctions and copy the director to a flash drive to load that drive in the isolated machine? How savefunctions works?thanks again

**Comment by Josue87** [comment]
Hi rusopro.

To work in an isolated environment, you can download the code beforehand and add a few small modifications so that instead of pulling our Git do it locally. Effectively with the "savefunctions" still part of the code uses the network, we are currently working on improving the functionality of saving iBombShell in the registry to work without network.
